### ISSUE TITLE
[WR] Use of schema.org

### ISSUE THREAD

**Issue by gkellogg** [w3c/pub-manifest#10]
* [ ] The spec describes the use of `https://schema.org` as a required element of `@context`. This is common practice, but @danbri has expressed frustration for schema.org being part of the execution path of JSON-LD. We recommend that processors cache popular contexts such as schema.org, and you might as well. As the JSON-LD WG is including embedded HTML support, including for contexts, it's possible that in the future, schema.org will not perform content negotiation at `https://schema.org` for `application/ld+json` and will instead include an embedded JSON-LD context in a script element which does something like load `http://schema.org/docs/jsonldcontext.json` through something like the following:
  ```html
  <html><head><script type="application/ld+json">
    {
      "@context": "http://schema.org/docs/jsonldcontext.json"
    }
  </script></head></html>
  ```
  I'm not sure what action you'd take upon something so prospective, particularly given that many specs reference `https://schema.org" (or equivalent), but you should be aware.

* [x] Some of the examples have invalid JSON syntax, for example the second part of [Example 5](https://w3c.github.io/wpub/#example-5-using-a-text-string-instead-of-a-person-object) is missing a comma (",") after `"type" : "Person"`. The JSON-LD specs have some infrastructure to extract all examples and perform validation of them (both syntactic and semantic), which can find such issues. Of course, this is not simple, but people copy and paste such examples, so it's good that they be validated.

* [x] In [Example 6](https://w3c.github.io/wpub/#example-6-resource-list-that-includes-one-link-using-a-relative-url-as-a-string-datatypes-svg-and-two-that-display-the-various-properties-of-the-a-linkedresource-object), the "resources" property describes that "datatypes.svg" is treated as a relative URL, however the term definition for "resources" seems inconsistent with this, as when this example is expanded ([playground link](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%5B%22https%3A%2F%2Fschema.org%22%2C%22https%3A%2F%2Fwww.w3.org%2Fns%2Fwp-context%22%5D%2C%22type%22%3A%22CreativeWork%22%2C%22resources%22%3A%5B%22datatypes.svg%22%2C%7B%22type%22%3A%22LinkedResource%22%2C%22url%22%3A%22test-utf8.csv%22%2C%22encodingFormat%22%3A%22text%2Fcsv%22%2C%22name%22%3A%22Test%20Results%22%2C%22description%22%3A%22CSV%20file%20containing%20the%20full%20data%20set%20used.%22%7D%2C%7B%22type%22%3A%22LinkedResource%22%2C%22url%22%3A%22terminology.html%22%2C%22encodingFormat%22%3A%22text%2Fhtml%22%2C%22rel%22%3A%22glossary%22%7D%5D%7D&context=%7B%22%40context%22%3A%7B%22vocab%22%3A%22http%3A%2F%2Fexample.com%2Fvocab%2F%22%2C%22property%22%3A%22http%3A%2F%2Fexample.com%2Fvocab%2Fproperty%22%7D%7D)) it is interpreted as a value.

* [x] [Example 8](https://w3c.github.io/wpub/#example-8-example-accessiblity-metadata-for-a-document-with-text-and-images-the-publication-provides-alternative-text-and-long-descriptions-appropriate-for-each-image-so-can-also-be-read-in-purely-textual-form) uses `ItemList` and `itemListElement`. Note that the values of `itemListElement` are not actually ordered, and order is specified using `itemListOrder` (which I suppose defaults to _Unordered_ or `schema:position` in a `schema:ListItem` value. By using `ItemList` it may give the impression that values of `itemListElement` are ordered, which they are not. You might want to be clear about this.

* [x] Note that the specification of text direction in JSON-LD is under active discussion (as @iherman well knows) and there is hope that some solution may be forthcoming.

* [x] The "links" property is described as having string values interpreted as URLs, but when trying this in the playground, they expand to values, not ids. The term definition for "links" should include `"@type": "@id"`.

* [x] Not schema.org related, but many properties (e.g., "encodingFormat") do not have a language. If it's possible that a publisher might put, say, `"@language": "fr"` in the context, this could cause properties that specifically should _not_ have a language to gain one. You might consider adding `"@language": null` to the term definitions of such properties.

**Comment by iherman** [comment]
In the new set up of a Publication Manifest ("just" a vocabulary) there is no word of a processor. I.e., the first bullet item is probably not relevant here.

All others have been taken care of; propose closing.
