### ISSUE TITLE
What are "html resources"?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#105]
How does a validator or user agent make sense of this requirement for alternate resources:

> Non-HTML resources SHOULD be expressed as LinkedResource objects with their encodingFormat values set.

If the media type isn't specified, how can it reliably be determined whether a resource actually is html or not short of inspecting the content?

Does it mean all resources without `encodingFormat` should be assumed to be html?

Is there a reason why HTML resources get a pass, or can this be generalized to all resources?

**Comment by llemeurfr** [comment]
I agree that this exception made for html resources defeats media-equality, i.e. the goal for Publications to represent with equal ease e-books (based on (x)html resources), audiobooks (pure audio resources) or visual narratives (pure image resources). 

We should delete this rule IMO.

**Comment by mattgarrish** [comment]
> If a user agent knows that a publication is an audiobook (from the conformsTo property) it will make its best to deal with resources from the reading order as audio content.

The odd thing is, we don't recommend the media type for resources in the reading order. It's only alternate resources, and only when they aren't html.

I'm guessing this came in from audiobooks and assuming the alternative would normally be html, but it doesn't really work in pub manifest where we can't assume what the core media type will be and what will be a replacement.

I know with HTML picture if you don't specify the type on a source the browser will only try that one source and then fail. We don't define a similar algorithm for how to handle `alternate`.

We probably need to think through what we expect to happen with `alternate` a bit more.

**Comment by iherman** [comment]
I believe this is a bug in the definition of `alternate`. 

For resources in general, there is already media-equality, to use @llemeurfr's term. Nowhere does it say that the resource, expressed as a single string in the manifest, is an HTML resource, and the processing step does not make it so either. I do not see any reason why it shold be different for `alternate`.

**Comment by iherman** [comment]
Oops... I see the original issue's (and also in #103) that:

> Non-HTML resources SHOULD be expressed as LinkedResource objects with their encodingFormat values set.

I wonder whether this remark should be modified, by saying

> Resources _SHOULD_ be expressed as LinkedResource objects with their encodingFormat values set.

and it is a _SHOULD_, meaning that if a media reference is expressed as a string, that there is no media type set. That should also address https://github.com/w3c/pub-manifest/pull/103#issuecomment-541199851

**Comment by mattgarrish** [comment]
> Resources _SHOULD_ be expressed as LinkedResource objects with their encodingFormat values set.

This makes the most sense to me, although I wonder if the warnings will prove a nuisance.

As I mentioned above, HTML doesn't recommend or require a media type for the alternatives you can list in `source`, but the penalty of not doing so is that browsers will only attempt to use one alternative and then give up on them. We should probably figure similar rules for how to process alternatives.

**Comment by iherman** [comment]
This is now part of the version merged from PR #103. @llemeurfr is it o.k. to close this issue?

**Comment by mattgarrish** [comment]
Actually, I didn't squeeze this one into #103. It still says "Non-HTML resources". I'll have it updated in the next PR, though, so going to leave it closed.

**Comment by iherman** [comment]
oops... ;-0
