### ISSUE TITLE
conformsTo single and/or array of literals

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#106]
`conformsTo` can be a string:

```
"conformsTo": "https://www.w3.org/TR/audiobooks"
```

but for the processing algorithm to make sense we can't rely on an array translation, otherwise the profile can't be determined until after the value normalization steps (too late), or would have to occur in the middle of them so any extension steps can be run (very odd).

In this one case, we should probably explicitly allow either a single value or array of values and leave it to user agents to check the value type while obtaining the profile.

**Comment by iherman** [comment]
Yes, it seems that the processing algorithm should begin by looking at this explicitly, a bit like it does for context, and the user agent should determine whether it can do something or not with that profile(s).

**Comment by mattgarrish** [comment]
Maybe the easy way out of this is to note in the explanation that at this stage of the processing algorithm, the value could be either a string or an array so the actual processing will need to take that into account.

I don't like the idea of altering the value type just to account for this one quirk in the algorithm.

**Comment by iherman** [comment]
I'm not sure I understand...

**Comment by mattgarrish** [comment]
I'm envisaging wording to obtain the profile like you put in #101, but also explaining why we talk about single values and lists in the explanation (i.e., that the normalization happens later).

That way we leave conformsTo as an "Array of Literals" even though it won't (always) be at processing time, or not until the end of the algorithm.

**Comment by iherman** [comment]
@mattgarrish, this seems to be settled in the version after the merge of #103 (modulo a separate comment https://github.com/w3c/pub-manifest/issues/101#issuecomment-542128872). If you agree, we should close the issue.

**Comment by mattgarrish** [comment]
Closing this with #116
