### ISSUE TITLE
require extension steps be identified by profile?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#107]
We define how to obtain the profile, but we don't use that information in the algorithm.

I wonder if we should say something in the profile requirements about identifying extension steps by profile identifier.

So in an extension, the infra prose might be something like:

> This specification extends the manifest processing as follows:
>
> (Step 6.8) When `profile` is 'https://www.w3.org/TR/audiobooks', run the following additional steps:
> ...

**Comment by iherman** [comment]
Except that... if profile _includes_ audiobooks rather than _is_...

**Comment by iherman** [comment]
I was wrong. The processing steps define the value of `profile` based on the values of `conformsTo`.

**Comment by iherman** [comment]
Issue is now handled via PR #103 (which has been merged) closing.
