### ISSUE TITLE
split processing functions

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#108]
Instead of saying to call "this step", it might make it easier to read to define the relevant steps as their own functions. It might be more obvious when properties are being recursively descended into, too.

**Comment by iherman** [comment]
I am not sure I understand...

**Comment by mattgarrish** [comment]
Sorry, I'm trying to write some code to match the algorithm to check that it works as expected, so making issues that are probably unreadable outside my brain.

An example here would be all the normalizing steps. Instead of having all these steps in the main algorithm, we could split them out. So section 6 might just say.

> For each `term` → `termValue` of `manifest`:
> 1. Let `normalized` be the result of calling normalize data given `term` and `termValue`.
> 2. Set `processed[term]` to `normalized`.

After the main processing algorithm we define "normalize data" as the series of steps to run and we can use generic variables.

That way when we need to descend into objects to process additional values, we say to run "normalize data" using the keys/values of that object instead of to run "this step" again. The function becomes self-contained and clearer, so we don't have to make sense of references to `manifest`/`processed` when we're really somewhere below that inside an object.

**Comment by iherman** [comment]
Ah... It is difficult to see in abstract whether it is helpful or not; my gut feeling says it is. But yield completely to your assessment on this!

**Comment by mattgarrish** [comment]
Closing this with #116
