### ISSUE TITLE
accessmodesufficient value type confusing

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#110]
The accessModeSufficient property expects one or more ItemList, but the value category says "Array of Literals".

We don't have a value type for an ItemList, so I'm not sure how to correct this. It's sort of like we want an "Array of Array of Literals".

**Comment by iherman** [comment]
Hm. This is now clearer in https://schema.org/accessModeSufficient (I remember this wasn't very clear before). We should probably refer to the Schema.org page, if we can, instead of reproducing the definition ourselves...

**Comment by mattgarrish** [comment]
It's not the definition that is the problem, though, but the value type category.

One thought would be to put "(None)" into the field and bypass trying to check this one with the value type step. The problem is it wouldn't normalize the value to an array, which seems necessary.

Or maybe we should define a generic 'Object' type and call it an "Array of Objects" so all that gets check is that each entry is a map. A later step could then verify the maps all represent ItemLIsts.

**Comment by iherman** [comment]
> Maybe we should define a generic 'Object' type and call it an "Array of Objects" so all that gets checked is that each entry is a map. A later step could then verify the maps all represent ItemLIsts.

Actually, this may be a good idea for possible future extensions.

**Comment by mattgarrish** [comment]
Closing this with #116
