### ISSUE TITLE
leave null languages alone?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#117]
Processing of the manifest results in a null language declaration being removed, but isn't this problematic?

What if you internalize into a JSON-LD object, for example, or want to write one back out? The language declarations that used to override a global declaration are now gone.

Should we just leave existing declarations alone?

**Comment by iherman** [comment]
The same happens in JSON-LD processing, see https://tinyurl.com/y2vejlb3

Writing out things back into JSON-LD would be complicated anyway. If one wants to really control that, it involves things like JSON-LD Framing which involves providing your own special context for that operation.

I would say leave it as is.

**Comment by mattgarrish** [comment]
But the `@context` is removed in the output of that example  so the globals don't persist. Should our algorithm do this?

**Comment by iherman** [comment]
Yes, that is also removed by the JSON-LD processor. I guess it can be removed, too, it does not have any usage in the generated data structure...

**Comment by mattgarrish** [comment]
> I guess it can be removed, too, it does not have any usage in the generated data structure...

Okay, that works for me. I just found it strange that the `@context` was still in the final data but not the language.
