### ISSUE TITLE
Removing faulty alternates?

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#122]
In the processing step 4.3.2.1/4, step on alternates, it says:

> if resource["alternate"] is set, for each alternate of resource["alterate"], if alternate["encodingFormat"] is not set, validation error.

Shouldn't, in the same spirit of the other checks, such a faulty alternate be removed from  resource["alternate"]?

**Comment by mattgarrish** [comment]
> Shouldn't, in the same spirit of the other checks, such a faulty alternate be removed from resource["alternate"]?

I don't believe so, no, as we only recommend that the `encodingFormat` be set. It's not an error.

**Comment by iherman** [comment]
Indeed. But this seems one of the rare cases when a validation error does not mean removal of the culprit. In some sense, this could be considered as a validation warning rather than an error...

**Comment by iherman** [comment]
Anyway, let us not complicate the processing by introducing yet another category beyond validation error and fatal error. Closing.

**Comment by mattgarrish** [comment]
> Anyway, let us not complicate the processing by introducing yet another category beyond validation error and fatal error.

Right, validation "errors" have two classes within them depending on whether you break a "should" or a "must". Not every broken "must" is fatal.

We could maybe note this in the error handling section - that the user agent should differentiate the severity as part of presenting the error to users.

Adding another class of error to the algorithm does seem like it might make things more complicated than needed.
