### ISSUE TITLE
What does it mean to retain entity properties?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#149]
This statement is a bit odd in the creators section:

> When compiling each set of creator information from a [schema.org] Person or Organization type, user agents MUST retain the properties defined for the Entity type, when available.

It seems to forbid our removing invalid properties. But, more importantly, why wouldn't valid properties be retained?

I _think_ we added this when we had a generic "creator" property back in the infoset days, but it doesn't seem like a useful statement to keep anymore.

**Comment by iherman** [comment]
I do not understand what this was all about. I think what we may wanted to say (and this is valid for the Publication manifest itself, too) is that the author _MAY_ add other properties to an Entity (presumably properties that are defined by schema.org) and our algorithm should not remove those. (I actually have a test case for that in my implementation.) But it is weird to have this difficult-to-parse statement here, so I agree it should be removed.

**Comment by mattgarrish** [comment]
> the author _MAY_ add other properties to an Entity

Right, and we sort of get at that after the entity object declaration with this statement:

> Note that user agents MAY interpret a wider range of creator properties defined by Schema.org than the ones in the preceding table.

But it might be useful to also change this to be clearer, though. Perhaps make it an actual note like the following:

"This minimal set of properties is not restrictive. Authors can include any additional properties defined for the `Person` and `Organization` types, as appropriate. User agents are similarly not limited to interpreting only the preceding properties."
