### ISSUE TITLE
Usage of JSON-LD language maps in WPM?

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#15]
(This is a spin-off from w3c/wpub#287; raised it separately to follow the discussions better.)

The current setup for localizable strings is to use either a simple string (inheriting the language set via `inLanguage`, if available, otherwise no language is provided) or an object of the form:

```json
{
	"@value" : "The string",
    "@language": "en"
}
```

When we have multilingual values, at the moment the only option is to use a mix of these in an array:

```json
{
   "name" : [
  	    "The Three Musketeers",
  	    {
            "@value": "Les Trois Mousquetaires",
            "@language": "fr"
        }
    ]
}
```

JSON-LD has an alternate notion, ie, language maps, that would allow a more consise formulation:

```json
{
   "name" : {
  	    "en": "The Three Musketeers",
        "fr": "Les Trois Mousquetaires"
    }
}
```

Question: should we rely on language maps _instead of_ (or maybe _additionally to_?) the current `"@value"`+`"@language"` approach?

**Comment by iherman** [comment]
I think one of the original issues, i.e., that schema.org processors do not understand language maps, still holds. Which may be (alas!) a showstopper...

Propose closing?

**Comment by aphillips** [comment]
The discussion of Japanese and various `ja-Kana` requirements reminds me to note: one reason why Japanese and Chinese data requires a second representation is for sorting. Generally the presentation of names and titles requires this additional metadata (in Japanese it is called `yomi`) that cannot be easily computed from the Han/kanji. This _is_ orthogonal to language maps. It is an additional features that publications need. Hence not reopening this issue. Just calling out that this may not be addressed by pub-manifest as a feature requirement.
