### ISSUE TITLE
Minor issues in the 'add HTML defaults' function

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#152]
* In the (1) step at the end: "approrpriate" -> "appropriate"
* "If `data["readingOrder"]` is not set or its value is an empty string or list": strictly speaking, it cannot be a string any more. Previous normalization steps would have turned it into an array. Furthermore, if the only string was, originally, an empty string, it would have been turned into a `['']` first, then into a `[LinkedResource]` with an entry without URL, that would have been filtered out, and then the empty list would have been removed. Ie, I believe, the only option is whether `data["readingOrder"]` is set or not...
* "append `document.URL` to `data["uniqueResources"]`." This should be preceded by a check whether the URL is already on that list or not.

**Comment by mattgarrish** [comment]
>     * "append `document.URL` to `data["uniqueResources"]`." This should be preceded by a check whether the URL is already on that list or not.

The infra definition of appending covers this:

> To append to an ordered set: if the set contains the given item, then do nothing; otherwise, perform the normal list append operation.

**Comment by mattgarrish** [comment]
Although, we could prepend in this case, since technically the reading order is supposed to be first. But we wouldn't issue a warning since the reading order is empty if we reach this step.

**Comment by iherman** [comment]
Ah, I forgot that this was an ordered set; the last remark is indeed irrelevant.

(I do not think we should prepend; we do not claim that the order of `uniqueResources` count.)

**Comment by mattgarrish** [comment]
>     * strictly speaking, it cannot be a string any more

Right, same is true for `name` which has to be an array of localizable strings by this stage. For both, we can simply test if the value is not set, as if either is an empty array they would have already been removed by the earlier step.
