### ISSUE TITLE
HML Defaults algorithm: is it necessary?

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#155]
Where in the current spec do we define the two rules that are encoded in the 'HTML Defaults' section (§5.4.3)? I do not find it in the current document… Isn't it possible that this is _not_ in the current spec any more? If so, we can:

a. define it as optional in §4 somehow insofar as saying "if the manifest is discovered via §4.1 or §4.2, then these and these defaults apply"
b. remove the whole thing altogether from the processing (which also means that the 'document' argument for the main algorithm becomes unnecessary)

I am more in favor of (a).

**Comment by mattgarrish** [comment]
Ya, we lost these when we the split from web publications. They were specific to WP and the PEP:

- https://w3c.github.io/wpub/#wp-reading-order
- https://w3c.github.io/wpub/#wp-title

What remains now is also confusing as reading order requires at least one resource even without adding the html doc, so there's no option for it to optional.

I think a) will work, but the doc also needs some other cleanup.
