### ISSUE TITLE
Introduction non-normative?

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#160]
I believe §1 (Introduction) is non normative. If so, it should be marked as such...

**Comment by mattgarrish** [comment]
That would make the scope, terminology and conformance keywords informative, but that seems wrong.

We could remove the introduction parent section, as the original introductory material has all been lost over time.

**Comment by iherman** [comment]
Then let's do the second...

**Comment by iherman** [comment]
Wait... what is today the scope section should still stay in its own introduction section (I think we are actually required to have an intro...), but move the terminology and conformance into a separate, normative section.
