### ISSUE TITLE
Note that list styling/numbering not preserved in toc?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#173]
Looking at toc tests, we don't specifically note that list styling/numbering isn't preserved in the authoring section, but css list styles and start numbers are not processed in the algorithm. Wondering if it might be helpful to be clear on this point for authors?

**Comment by dauwhe** [comment]
We could also remind authors that inline markup in TOCs might be thrown away.

**Comment by mattgarrish** [comment]
Yup, and the number of levels of links the UA will actually provide access to is also discretionary, as we don't require anything by way of presentation. There should be more warning that the UA toc is not intended to be a replica of the authored html rendering.
