### ISSUE TITLE
authoring requirement for first "doc-toc" element doesn't match fragment change

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#174]
I noticed in the toc authoring section that it still says the table of contents must be the first element with that role, although by allowing fragments the need for that to be true is gone (i.e., if not identified by a fragment, find the first doc-toc role).

**Comment by iherman** [comment]
Yep, there is a slight mismatch. Would it help if, in the first paragraph of C.2 we said that it _SHOULD_ be the first element (rather than _MUST_)? That is then in line with the first step in C.3.

**Comment by mattgarrish** [comment]
> Would it help if, in the first paragraph of C.2 we said that it _SHOULD_ be the first element (rather than _MUST_)?

Ya, that's probably good enough.

**Comment by mattgarrish** [comment]
Closing with #191.
