### ISSUE TITLE
table of contents can be hidden?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#175]
The only requirement right now is that the table of contents be identified by fragment or that it be the first element in document order with the role doc-toc.

Does that still apply if the toc itself is a hidden element, or inside one? Right now, nothing says this is invalid. We only ignore hidden content within the toc itself.

**Comment by iherman** [comment]
Although a pathological situation, I think it is allowed. A user agent MAY choose to extract the ToC from a resource and display the ToC using its own means, and the author may, therefore, choose to hide the ToC to avoid a double ToC situation.

**Comment by mattgarrish** [comment]
I wouldn't even call it pathological. It's fitting with the idea that sometimes you just want a toc for machine processing, not display, and that creating a separate document that isn't in the reading order for that purpose isn't always wanted or absolutely necessary.

As far as I understand HTML authoring of hidden content, it's not invalid, either. The hidden toc is not for use in any specific presentation on the page, but is hidden from all views (AT, etc.) because it is solely for script processing. Scripts are allowed to process hidden content.

I think we should just note that the first doc-toc means hidden or not.

**Comment by mattgarrish** [comment]
Closing with #191.
