### ISSUE TITLE
table of contents in a sectioning element

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#176]
While we are clear that the first doc-toc is the toc when a fragment identifier isn't supplied, is this potentially problematic given that a sectioning element (article, aside, etc.) could have its own toc and occur first?

This probably falls into the highly unlikely scenarios and may not be worth worrying about, but just has me wondering. I'm not even sure there's a good solution without always requiring a fragment identifier, as the nav could be inside a section (i.e., we'd start to get into picking and choosing sectioning elements).

**Comment by iherman** [comment]
Clearly, the 'first doc-toc' is brittle, and the better way of doing this is to use the fragment ID. We could add an editorial note accordingly. But, otherwise, I believe we should keep it at that...

**Comment by mattgarrish** [comment]
Identifying the toc with 'doc-toc' seems a bit unnecessary when allowing fragment identifiers. I wonder if we should say that only matters when the toc isn't specifically identified by a fragment, with the note that it is always best to be specific?

Does the user agent reject an element with a matching ID if the element doesn't have the role on it, even if there is a processable list of links inside?

**Comment by iherman** [comment]
I think at least a warning would be appropriate. As far as I understand, the presence of doc-toc has accessibility implications, and we should push for that...

**Comment by mattgarrish** [comment]
Thinking about this again, I find it all a bit muddled.

While I don't like relying on finding an element with a role, are we causing other problems by allowing fragments?

Namely, how do you avoid resource duplication when a fragment might mean different things in different contexts. For example, say I want to link to my toc that's embedded in a bunch of front matter. Will the fragment be interpreted as where to start reading by the user agent unless I duplicate an entry so that the fragment-less one is in the reading order and the fragment-id'd one is in the resources? But if I do that, it causes duplication of resources so the entry that's referencing the toc gets tossed out during processing and is no longer available.

We might want to consider going back to only finding the toc by role and just live with the one in a million publications that can find a legitimate reason for having a toc for something else first.

**Comment by iherman** [comment]
> We might want to consider going back to only finding the toc by role and just live with the one in a million publications that can find a legitimate reason for having a toc for something else first.

This may be the wisest approach after all. 

Also, there are three places where this whole issue appears: §4.8.1.3 and §C.1 for the manifest spec and §4.2 in the audiobook spec. None of these mention fragments, they only refer to the resource as a whole. I would think we can take out the fragment issue from our discussions...

**Comment by mattgarrish** [comment]
Closing this with the changes in #192
