### ISSUE TITLE
split toc a element relations into a list

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#177]
We should probably state to split on whitespace and create a list from the attribute when processing since `rel` can contain 0..n relations (even if there are few useful rel values for a link in a table of contents).

Right now we just say to trim the value and copy it over, so any values are still concatenated together as a string.

**Comment by iherman** [comment]
You mean in 6.2.4 ? Yep.

**Comment by iherman** [comment]
(I may have to take a deep breath and implement the TOC extraction, too:-)
