### ISSUE TITLE
toc processing note, sounds grammatically funny to me

### ISSUE THREAD

**Issue by jccr** [w3c/pub-manifest#181]
The language of the [note in C.3](https://github.com/w3c/pub-manifest/blob/master/index.html#L4745) sounds funny to me:
> User agents can process and internalize the resulting structure **in whatever language and form is appropriate.**

How about this instead?
> User agents can process and internalize the resulting structure in whatever language and form **that is** appropriate.

**Comment by mattgarrish** [comment]
Sidestepping "that" issue, I have a different concern with the use of "form". The form is not open to interpretation, only the specific variable type you use to represent it (hash, associative array, object).

The note might be better rewritten along the lines of: 

"User agents can process and internalize the resulting structure using any language that can represent the final form of the data."
