### ISSUE TITLE
drop requirement for https for schema.org?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#188]
I noticed this statement in the manifest context section:

> Although Schema.org is often referenced using the http URI scheme, the vocabulary is being migrated to use the secure https scheme as its default. **The use of https when referencing Schema.org in the manifest is REQUIRED by this specification.**

Does this really matter, and how are we supposed to enforce it? https is required in the context URL, so that's already covered, otherwise we don't reference schema.org URLs (except in the context document, which we also control).

Any reason not to drop it?

**Comment by iherman** [comment]
Just commented in the PR #189

**Comment by mattgarrish** [comment]
Closing with changes in #189.
