### ISSUE TITLE
tiny remark on profiles and contexts

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#193]
(Referring to the latest, Jan 28 version of the draft): the text says

> (§ 4.3 Manifest Contexts) If a profile requires additional validation of the manifest context, those steps are performed here.

It may be worth emphasizing that this step may lead to a fatal error (e.g., missing context). This is a warning for implementers that they should be prepared to such a status and abort all other processing...

(Apologies for not having realized that when it was still a PR. The downside of doing such reviews at an airport...)

**Comment by mattgarrish** [comment]
Is it any different than any other step, though? It all depends on what has to be validated in the context. I tried to keep the wording open-ended, as the extension step(s) could be to check a context URL or some other parameter.

Fatal errors can occur anywhere so long as whatever issue it is makes it impossible to handle the publication.

**Comment by iherman** [comment]
On 29 Jan 2020, 00:18 +0100, Matt Garrish <notifications@github.com>, wrote:
> Is it any different than any other step, though? It all depends on what has to be validated in the context. I tried to keep the wording open-ended, as the extension step(s) could be to check a context URL or some other parameter.
> Fatal errors can occur anywhere so long as whatever issue it is makes it impossible to handle the publication.

Ah. I missed that, but you are probably right. (I will have to check my implementation…)
