### ISSUE TITLE
Checking agains null or '' in the toc algorithm, 4.5?

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#195]
The current TOC algorithm says, in C.3.4.5.2.

```
If current_toc_node["name"] is an empty string:
```

However, the latest spec has changed, in C.3.4.4 the initialization of the `current_toc_node` to `null` everywhere, so the case of an empty string at that place isn't happening. Shouldn't it say"

```
If current_toc_node["name"] is null
```

Note that if this is so, the whole of that part can be simplified, because null is set explicitly.

(By setting the algorithm to what it says in the text, at least my implementation failed on tests `c2.ignored.{02,03,04}`.)

**Comment by mattgarrish** [comment]
The test should be for both null and an empty string, as far as I can tell.

It could be null after processing a list item if a title isn't found, but it could also potentially be an empty string if, for example, an `<a><img src="..."/></a>` tag is inserted (or anything else like that that would result in no text content).
