### ISSUE TITLE
are rel values case sensitive?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#196]
I noticed that in the definition and algorithm we don't mention anything about case-insensitively matching rel values, but case insensitivity is the default for html (https://html.spec.whatwg.org/multipage/links.html#linkTypes).

Whether we want case sensitivity or not, we should make it clear which we expect in both places.

**Comment by dauwhe** [comment]
I'm sTRongly iN faVOR oF CAse-inSEnsitiVity.

**Comment by iherman** [comment]
I agree we should be case-insensitive...
