### ISSUE TITLE
Update manifest properties vocabulary and namespace?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#2]
The custom properties incorporate "WP" into their namespace:

> https://www.w3.org/ns/wp#inDirection

Should we also change this to "pub"?

Also, following the URL takes you to the "Web Publication Manifest Vocabulary". We should definitely rename that.

**Comment by iherman** [comment]
Yes, definitely, we should rename this. What I propose:

- the context should be https://www.w3.org/ns/pub-context
- the namespace for our terms should be https://www.w3.org/ns/pub
- of course, the document should say "publication manifest vocabulary"

**Comment by iherman** [comment]
The new vocabulary files are in place.
