### ISSUE TITLE
Problem with the WebIDL for accessModeSufficient

### ISSUE THREAD

**Issue by llemeurfr** [w3c/pub-manifest#206]
The spec defines `accessModeSufficient` ([section 4.7.1.2](https://www.w3.org/TR/pub-manifest/#accessibility)) as an Array of Objects + required value is One or more ItemList. 

An example in the spec is found [here](https://www.w3.org/TR/pub-manifest/#example-19-setting-accessiblity-metadata-for-a-publication-that-provides-alternative-text-and-long-descriptions-appropriate-for-each-image-enabling-it-to-be-read-in-purely-textual-form) and [here](https://www.w3.org/TR/pub-manifest/#example-75), where the property is an array of ItemList objects with an itemListElement property (which is an array) and a description. This is consistent with the definition found in schema.org. 

But the [WebIDL](https://www.w3.org/TR/pub-manifest/#webidl-wpm) specifies it as a sequence of DOMString, which is not compliant with the spec. 

The WebIDL must therefore be corrected. 

Note that from a reading system perspective, we'll follow the [schema.org techniques](https://w3c.github.io/publ-a11y/UX-Guide-Metadata/techniques/schema-org.html#screen-reader-friendly) for implementing a good UI in Thorium Reader (and maybe the "R2 Reader" mobile test apps).

**Comment by mattgarrish** [comment]
Yes, the property was originally put in as a comma-separated string of values which is what that webidl value probably comes from.

I assume we can use `sequence<Object>` for this to match our general object definition.

**Comment by mattgarrish** [comment]
Closing with #209
