### ISSUE TITLE
data models appendix only has one

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#211]
Appendix A talks in the plural about data models even though we only have a webidl definition. We did this as there were discussions about adding some additional informative models in the future, but I'd say the future is here and we're not adding any more.

My preference would probably be to leave it alone and maybe just add a note that more models could be added in future revisions.

Alternatively, though, we could make the heading singular, strip out the A.1 heading, and change this one sentence to refocus on webidl:

"This appendix provides <ins>an</ins> informative abstract data model<del>s</del> <ins>in WebIDL</ins> that describe<ins>s</ins> the resulting data structure."

**Comment by iherman** [comment]
The second option is cleaner, and it is the kind of editorial change that is perfectly fine in CR phase, too. I would vote for that one...
