### ISSUE TITLE
Question regarding recursive normalization

### ISSUE THREAD

**Issue by naglis** [w3c/pub-manifest#235]
In 7.4.1 [step 9.a.i](https://www.w3.org/TR/pub-manifest/#normalize-recurse) it says:
> if `item["type"]` is set and includes a [recognized type](https://www.w3.org/TR/pub-manifest/#dfn-recognized-types), [for each](https://infra.spec.whatwg.org/#map-iterate) `key` → `keyValue` of `item`, set `key` to the result of running [normalize data](https://www.w3.org/TR/pub-manifest/#processing-normalize), when successful, given `key`, `keyValue`, `lang`, `dir`, `base` and using `keyValue["type"]` as the context. If failure is returned, [remove](https://infra.spec.whatwg.org/#list-remove) `key` from `item`.

Depending on context, `type` can be an array of literals, so in theory, there can be more than one recognized type, e.g. introduced via profile? From the current description it seems that the recursive normalization on `item` should be called once (_includes a recognized type_) in the context of the first recognized type? But that would potentially leave unnormalized values in `item` for `key`s from other contexts and it would also depend on the order of types in `item["type"]`?

IIUC, the same applies to 7.4.1 [step 9.b.i](https://www.w3.org/TR/pub-manifest/#normalize-recurse).

**Comment by iherman** [comment]
Profiles have the possibility to extend the processing steps. If a profile adds a type that can be used _alongside_ another recognized type, then the profile specification has to amend that step explicitly.

I believe that making the general algorithm even more complicated to be prepared for a remote possibility would just create problems.

**Comment by iherman** [comment]
@naglis, is it ok. to close this issue?

**Comment by naglis** [comment]
@iherman yes, thank you for the clarification.
