### ISSUE TITLE
Possible typos

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/pub-manifest#246]
Hello from Tokyo.

I am translating the "Publication Manifest" specification into Japanese now.
Thank you for the great specification!

I found some possible typos:

Sec. 1.4 - "a many" might be "many".
Sec. 4.8.1.1 - "MAY specified" might be "MAY be specified".

Best regards,

KAMITSUNA Shuji,

**Comment by iherman** [comment]
Thank you @shujikamitsuna, I agree with both of your comments. I marked this issue as an official (Editorial) Errata, to be handled when the document is republished.

Cc @mattgarrish @wareid

**Comment by iherman** [comment]
@mattgarrish @wareid we will have to agree how to process with such errata. My proposal is to update the editor's draft, and make clear in the changes' section that editorial errata have been handled (no need to list each of them individually). This issue is good enough as a record imho.

**Comment by wareid** [comment]
I agree, that is probably the best way to handle them all for now.
