### ISSUE TITLE
Broken fragment

### ISSUE THREAD

**Issue by shujikamitsuna** [w3c/pub-manifest#247]
Japanese translation is completed. Thank you for the great specification.
http://www.asahi-net.or.jp/~ax2s-kmtn/internet/publishing/REC-pub-manifest-20201110.html

A broken fragment, "https://infra.spec.whatwg.org/#parse-json-into-infra-values", has been reported on registering it into the W3C translation database. Please refer to:
https://validator.w3.org/checklink?uri=https%3A%2F%2Fwww.w3.org%2FTR%2F2020%2FREC-pub-manifest-20201110%2F&hide_type=all&depth=&check=Check

Best regards,
KAMITSUNA Shuji

**Comment by iherman** [comment]
@mattgarrish : indeed. It seems that the only existing fragment ID that we can use is simply `json`.

I have marked this as an erratum. I am not sure how we have decided to handle errata like this; I guess we can simply update the editor's draft.

@wareid @TzviyaSiegman @GarthConboy

**Comment by wareid** [comment]
If that's the best we can do for now, I'm fine with it.

**Comment by mattgarrish** [comment]
> It seems that the only existing fragment ID that we can use is simply `json`.

It looks like it's now: https://infra.spec.whatwg.org/#parse-a-json-string-to-an-infra-value

Compare with: https://web.archive.org/web/20200805074756/https://infra.spec.whatwg.org/#parse-json-into-infra-values

(What a joy "living standards" are!)

**Comment by mattgarrish** [comment]
This is the same broken link reported by the bot in #255. It will be fixed by pull request #256.
