### ISSUE TITLE
Lack of publication type a fatal error?

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#25]
I noticed that the canonicalization algorithm is expected to terminate if either the context or type are not set: https://w3c.github.io/pub-manifest/#canon-min-req

This makes sense for the context, since it wouldn't be clear that you have a manifest and not something else, but should the lack of a type be fatal or just a warning? It would be easy enough to default to CreativeWork, for example.

**Comment by iherman** [comment]
I think it should be a warning. I would expect a reader to happily go on without the type, actually, the problem arises if the manifest is 'used' by a schema.org processor (their tool certainly complains and stops, I do not know what the real search engine does in this case).
