### ISSUE TITLE
Typo? 'readingDirection' should be 'readingProgression'

### ISSUE THREAD

**Issue by MurakamiShinyu** [w3c/pub-manifest#250]
§4.7.1.10 Reading Progression Direction <https://w3c.github.io/pub-manifest/#reading-progression-direction> says:

> The reading progression is expressed using the <code>readingDirection</code> property.</p>

I think this should be:

> The reading progression is expressed using the <code>readingProgression</code> property.</p>

**Comment by iherman** [comment]
Thank you @MurakamiShinyu, added as an official erratum. Should be fixed at our next release.

@mattgarrish
