### ISSUE TITLE
"readingProgression" is missing in the Publication Manifest Schema

### ISSUE THREAD

**Issue by MurakamiShinyu** [w3c/pub-manifest#251]
["readingProgression"](https://www.w3.org/TR/pub-manifest/#reading-progression-direction) is missing in the Publication Manifest Schema, <https://github.com/w3c/pub-manifest/blob/main/schema/publication.schema.json>.

I think that the following definition needs to be added to the "properties" in this schema:

```json
		"readingProgression": {
			"type": "string",
			"enum": ["ltr", "rtl"],
			"default": "ltr"
		}
```

**Comment by iherman** [comment]
@MurakamiShinyu thanks, this is indeed a bug.

@mattgarrish @wareid this can be edited and changed on the repo without further ado, it is not part of the normative text. I will raise a separate PR for it.
