### ISSUE TITLE
Typo in normalize URLs explanation

### ISSUE THREAD

**Issue by naglis** [w3c/pub-manifest#253]
In the [normalize URLs explanation](https://www.w3.org/TR/pub-manifest/#normalize-urls) example the relative URL `chapter01.html` becomes `chater01.html` (missing `p`) in the absolute URL.

https://github.com/w3c/pub-manifest/blob/08e2a13456050c728607f687891429eb34484d40/index.html#L3472

**Comment by iherman** [comment]
Thanks @naglis, this is indeed an editorial bug. I have added it to the official list of errata, to be handled if and when we re-publish the spec.

cc @wareid @mattgarrish

**Comment by iherman** [comment]
Summary: change the URL in line 3472 to `.../chapter01.html`
