### ISSUE TITLE
json-ld reference

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#29]
We should reference JSON-LD 1.1 as it will be going to REC around the same time, but it's not clear if our current unnumbered specref reference will auto-updated when that specification gets published.

**Comment by iherman** [comment]
Raised an issue in the JSON-LD WG: https://github.com/w3c/json-ld-wg/issues/103. I think we should keep to json-ld now, and cross this bridge when we get there...

**Comment by iherman** [comment]
See https://github.com/w3c/json-ld-wg/issues/103#issuecomment-527464634.

Executive summary: the 'json-ld' reference will automatically redirect to the new Rec when that comes.
