### ISSUE TITLE
Review of i18n self-review

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#39]
I have done the official i18n self-review in issue #38. Before adding the extra label to ping the i18n people, the WG should have a look at the individual items and, if possible, check whether I have made a mistake.

I have left two issues open:

- It should be possible to associate a metadata-type language declaration (which indicates the intended use of the resource rather than the language of a specific range of text) with multiple language values. [more](https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta)
- Consider whether it would make sense to have one or more extra fields, in addition to the full name field, where users can provide part(s) of their name that you need to use for a specific purpose. [more](https://www.w3.org/International/questions/qa-personal-names#splitting)

We do not fulfill those, and the question is whether we have proper arguments to stay that way or whether we would add additional features accordingly. The translation, into our world, is:

- At the moment we have the `inLanguage`, defined as a _single_ language tag, and that signals the publication's language and the default language used for the metadata terms (title, etc). Do we need the possibility to have an _array_ of languages? What happens with multilingual ebooks, for example?
- At the moment the name of a person is one or several text terms (i.e., the person's name in English and Japanese). Do we need extra fields (an example is to specify the name used for sorting)? If so, how do we do that, knowing that having universal vocabularies for names can quickly become a very complicated nightmare...

I think, for both cases, the responses should be based on industry practice and business usage...

**Comment by laudrain** [comment]
@iherman 
Multilingual books are for a monolingual audience. That's first example in [more](https://w3c.github.io/bp-i18n-specdev/#sec_lang_meta).
But it is useful to have transliterations in metadata, i.e. titles and/or author names of a Japanese book also transliterated in latin characters.

It is also a good practice to give in the metadata for the user library, author names in sorting order (Herman, Ivan ; Audrain, Luc), besides classical string (Ivan Herman; Luc Audrain).
That's a given in the ONIX feeds for digital webstores and libraries.

**Comment by iherman** [comment]
> Multilingual books are for a monolingual audience. That's first example in more. But it is useful to have transliterations in metadata, i.e. titles and/or author names of a Japanese book also transliterated in latin characters.

... which, in fact, we do have, because the title term (`name` in the manifest) is an array of `LocalizableString`, i.e., one would add the title is as many languages/scripts as needed. So far so good.

However, the question is whether the `inLanguage` term, currently in the manifest (and inherited from schema.org) should be a single language tag or whether it could be several. E.g., if one takes one of those dual-language books with a text, and its translation, displayed side-by-side.

(It is perfectly fine if we say that this type of usage is so marginal, that we do not want to take that into account for the time being.)

**Comment by iherman** [comment]
> It is also a good practice to give in the metadata for the user library, author names in sorting order (Herman, Ivan ; Audrain, Luc), besides classical string (Ivan Herman; Luc Audrain).
That's a given in the ONIX feeds for digital webstores and libraries.

Yep, that is the example I was wondering about. AFAIK, there was a term for this in EPUB, and I do not know whether it was widely used.

The additional problem is that this is a specific example; if we go down that route, there might be other issues coming up and the metadata on persons might become extremely complicated...

**Comment by laudrain** [comment]
@iherman ah, ok.
So for multilingual book the inLanguage term should be able to bear multiple language terms.
So do we do in our catalog system where we describe all the languages of the title, and we also propagate this in ONIX.

**Comment by llemeurfr** [comment]
EPUB allows multiple languages. Therefore the Readium Webpub manifest, which can represent the "projection of an EPUB on the Web", defines [language as an array](https://readium.org/webpub-manifest/contexts/default/#language). 
The mapping from EPUB is defined [here](https://github.com/readium/architecture/blob/master/streamer/parser/metadata.md#language). It introduces the notion of "primary" language, the one used for e.g. choice of hyphenation mode.

I believe the W3C PubManifest should also allow for multiple `inLanguage` values + a rule on the "primary" one.

**Comment by llemeurfr** [comment]
Re. name variants, `sortAs` is the only variant we found useful at Readium, see introduction [here](https://github.com/readium/architecture/blob/master/streamer/parser/metadata.md#contributors). But I think the idea was dismissed by the WG in another thread, dommage.

**Comment by iherman** [comment]
(This thread shows how useful the i18n review is:-)

I try to summarize, and make them more specific, the various ideas so far, to facilitate a possible decision on Monday...

1. We keep `inLanguage` and `inDirection` pair as a single value each that provide the (default) language and base direction _for the text values used in the manifest_. (Keeping `inLanguage` is probably required to be compatible with its usage in schema.org) 
2. We define a new term called, say, `pubLanguage`, as an array of BCP47 terms, denoting the various languages used _in the publication_. If the term is not used in the manifest, but `inLanguage` is present, the latter becomes the (only) term for `pubLanguage`.
    * actually, the values in that array may have to be an object with language and base direction...
3. We define extra terms, say, `primaryPubLanguage` and `primaryPubDirection` for denoting the one in `pubLanguage`. Alternatively, we say that the first entry in the array is the primary language and direction. (Care should be taken in the JSON-LD context file so that the value is indeed ordered in JSON-LD, too. That can be done as well)

It is a bit messy, mostly due to the base direction issue, but can be worked out.

(I am not _proposing_ this yet, just trying to summarize...)

**Comment by iherman** [comment]
Refining https://github.com/w3c/pub-manifest/issues/39#issuecomment-524345750 a bit... I would think that the use cases we have do not require the base direction for the publ. language. The real linguistic content for the publication is _not_ in the manifest but, mostly, in HTML, and those can take care of the direction. The use case we have is really the language information, which is not for controlling _display_ but as metadata. Here is a revised, and simpler version of my proposal:

1. We keep `inLanguage` and `inDirection` pair as a single value each that provide the (default) language and base direction _for the text values used in the manifest_. (Keeping `inLanguage` is probably required to be compatible with its usage in schema.org
2. We define a new, pub-manifest specific term called, `pubLanguage`, as an array of BCP47 terms, denoting the various languages used _in the publication_. If the term is not used in the manifest, but `inLanguage` is present, the latter becomes the (only) term for `pubLanguage`.

    The term is order preserving (i.e., the value is a _list_, in JSON-LD/RDF parlance). The first item denotes the publication's "primary" language.

In contrast to https://github.com/w3c/pub-manifest/issues/39#issuecomment-524345750, which was only a summary, this is actually my _proposal_ to move ahead with this issue.

**Comment by iherman** [comment]
Refining https://github.com/w3c/pub-manifest/issues/39#issuecomment-524345750 a bit... I would think that the use cases we have do not require the base direction for the publication language. The real linguistic content for the publication is _not_ in the manifest but, mostly, in HTML, and those can take care of the direction. The use case we have is really the language information, which is not for controlling _display_ but as metadata but metadata issue, e.g., for sale. 

Here is a revised, and simpler version of the summary:

1. We keep `inLanguage` and `inDirection` pair as a single value each that provide the (default) language and base direction _for the text values used in the manifest_. (Keeping `inLanguage` is probably required to be compatible with its usage in schema.org
2. We define a new, pub-manifest specific term called, `pubLanguage`, as an array of BCP47 terms, denoting the various languages used _in the publication_. If the term is not used in the manifest, but `inLanguage` is present, the latter becomes the (only) term for `pubLanguage`.

    The term is order preserving (i.e., the value is a _list_, in JSON-LD/RDF parlance). The first item denotes the publication's "primary" language.

In contrast to https://github.com/w3c/pub-manifest/issues/39#issuecomment-524345750, which was only a summary, this is actually my _proposal_ to move ahead with this issue.

---

Comment on the intro text: we already _do have_ the [`readingProgression` term](https://w3c.github.io/pub-manifest/#reading-progression-direction) for the direction specific but publication level aspect that we have identified.

**Comment by iherman** [comment]
As a comment to the second question (related to names) we should note that text fields related to names appear, in the case of the pub manifest, _exclusively_ as part of [schema's Person](https://schema.org/Person). At the moment, we do not add any pub specific terms to that structure, we just "call out" some terms as being central (e.g., `name` or `id`). That includes things like given or family names. I would think that we should leave the issue and intricacies of name terms to schema.org... (We may want to raise an issue by schema.org on the sorting aspect, though.)

**Comment by llemeurfr** [comment]
Re. inLanguage, a simpler solution would be to state that if not expressed at the level of the property itself, the language of a localizable metadata is considered to be the main language of the content, as expressed in inLanguage. 
When this is not the case, overloading this default value with a local language is a proper way to go.

**Comment by iherman** [comment]
> Re. inLanguage, a simpler solution would be to state that if not expressed at the level of the property itself, the language of a localizable metadata is considered to be the main language of the content, as expressed in inLanguage.

I am not sure I understand...

**Comment by llemeurfr** [comment]
If I set "inLanguage":"en" I mean that content And metadata are in English. 
If I add, on a localizable property, "language":"fr" I mean that this property is in French.
If all metadata properties are in French, as there is no generic property to indicate that, I must add "language":"fr" on each property. 

ok the issue is that I now have an `inDescription` property, used to express the base direction of metadata content only, and no more `inLanguage` property reserved for expressing the language of metadata: this is annoying.

**Comment by iherman** [comment]
(I presume you meant `inDirection` and not `inDescription`...)

> After all your solution is more robust, even if it adds yet another property.

I believe having the new property is cleaner.

I also think that, in the vast majority of the cases, the `inLanguage` will suffice: after all, the metadata language and the publication's language are usually identical. But for publishers publishing in a multilingual world the new property, and the possibility of adding several languages, might be a reasonable thing to do.

**Comment by iherman** [comment]
This issue was discussed in [a meeting](https://www.w3.org/publishing/groups/publ-wg/Meetings/Minutes/2019/2019-08-26-pwg#section3).

- `RESOLVED:  create a PR along the lines of comment on issue #39 and this would close issue #39`
<details><summary><i class="differentiate">View the transcript</i></summary>
Wendy Reid: See Issue #39<br/>
Ivan Herman: See proposal to resolve #39<br/>
Ivan Herman: This has come up with the internationalization. There are 2 issues with the language. One is that we do set the language of the manifest - what we say is that the language setting we have is for the textual entries of the manifest and the publication as a whole…<br/>
… so we are conflating 2 different things. In many cases, those two languages are the same, but I can imagine publishers publishing a language book, which has one or more languages inside and on the other hand, the metadata is in a different language.<br/>
… this conflation is too narrow in some cases - and that’s the kind of question I saw there. I came up with a proposal for simple cases its’ fine, but we introduce a new term - publication language - which could be an array/list of languages<br/>
… these can be different in what we set for the manifest. If the property is not used, it’s the same as the manifest, but we leave the door open for additional terms. That’s my proposal<br/>
Wendy Reid: OK - does anyone have questions or comments?<br/>
Laurent Le Meur: I answered already that I agree. It seems the most robust solution, but in the wording, let’s be careful that the languages are set - the implementors must know what is the primary language of the content showing to the user. It should be pub language.<br/>
… I think that the best solution is that if pub language exists, that’s the primary.<br/>
Proposed resolution: create a PR along the lines of comment on issue #39 and this would close issue #39 (Ivan Herman)<br/>
Garth Conboy: +1<br/>
Wendy Reid: +1<br/>
Laurent Le Meur: +1<br/>
Bill Kasdorf: +1<br/>
Nick Ruffilo: +1<br/>
Brady Duga: +1<br/>
Dave Cramer: 0<br/>
Resolution #2: create a PR along the lines of comment on issue #39 and this would close issue #39<br/>
Dave Cramer: I’ve just suffered too much from these discussions with epub - the language of the publication and the metadata, and what if they don’t match… Leaving as much to the content is a good thing - just makes me nervous…<br/>
</details>

**Comment by iherman** [comment]
Unfortunately, while working out the details, I realized that I have made a mistake in https://github.com/w3c/pub-manifest/issues/39#issuecomment-524611246. My apologies.

The point is: having looked at the definition of [`inLanguage`](http://schema.org/inLanguage) I realized (although the definition is a big vague) that, in our terminology, _`inLanguage` sets the language of the publication content_. In other words, it should be just the other way round than what is proposed in https://github.com/w3c/pub-manifest/issues/39#issuecomment-524611246.

I also tested the [structured data testing tool](https://search.google.com/structured-data/testing-tool) and, at least that tool does _not_ complain if the value of `inLanguage` is an array of language tags instead of a single value. In other words, the role played by `pubLanguage` in my earlier (erroneous) proposal in https://github.com/w3c/pub-manifest/issues/39#issuecomment-524611246 can, and should be played by the `inLanguage` tag. The only change to be done in the specification is to make it clear that the value of the property can also be an array bcp47 tags.

---

Where does it leave us for the language of the textual content in the manifest? There _is_ a bona fide JSON-LD way of doing that, which is using `@language`. I.e., one could say:

```json
{
    "@context" : [
        "https://schema.org",
        "https://www.w3.org/ns/pub-context", 
        {"language":"fr"}
    ],
    "name" : "Le roi René"
}
```

unfortunately, the syntax should be as it is in the example, and it ain't pretty.

Here are our alternatives as I see it (remember that each textual term _can_ set the language independently, we are talking about the default):

1. we introduce this syntax into our "shape" of JSON-LD for the manifest, ie, that should be the way of setting the language of the text terms.
2. we keep to the current setup whereby the value of `inLanguage` (or, more precisely if we allow for an array: the first entry of the array) serves as an implicit language value for a textual manifest content.
3. we could allow for both: we add `{"language":..}` to our manifest, but (2) is left as a fallback in case it is not there.

Thoughts?

cc @llemeurfr @wareid @mattgarrish @dauwhe

**Comment by llemeurfr** [comment]
The syntax imposed by JSON-LD to the use of `language` appears a bit too ugly to be adopted. The context should be stable, not touched for a given manifest. 

`inLanguage` and `inDirection` seemed to act as a pair until you pointed that schema.org defines the former as the language of the content, while the latter is the direction of metadata values. 

So ok for extending the definition of `inLanguage` by adding that it is also the default language of metadata values (textual manifest values as the spec says).

**Comment by iherman** [comment]
> `inLanguage` and `inDirection` seemed to act as a pair until you pointed that schema.org defines the former as the language of the content, while the latter is the direction of metadata values.

(Beware! Bike-shedding danger!) Right. Actually, that made me realize that we may want to use a different term for `inDirection`, to emphasize that this term is the default base direction for textual content of the metadata items, and _not_ for the real content (which has its own ways of setting the direction). Maybe just using `baseDirection` is better.

**Comment by iherman** [comment]
Closing the issue, the review ended
