### ISSUE TITLE
Editorial error in § 2.7.3.6.2 Item-specific Language

### ISSUE THREAD

**Issue by xfq** [w3c/pub-manifest#46]
§ 2.7.3.6.2 Item-specific Language
https://www.w3.org/TR/pub-manifest/#manifest-specific-language-and-dir

The last two paragraphs are almost the same:

> Once the base direction has been identified, user agents MUST determine the appropriate rendering and display of natural language values according to the Unicode Bidirectional Algorithm [bidi]. This could require wrapping additional markup or Unicode formatting characters around the string prior to display, in order to apply the base direction.

> Once the base direction has been identified, user agents MUST determine the appropriate rendering and display of natural language values according to the Unicode Bidirectional Algorithm[bidi]. This could require wrapping additional markup or control characters around the string prior to display, in order to apply the base direction. (See § D. Examples for bidirectional texts.

**Comment by iherman** [comment]
Oops... essentially a copy-paste error. 

Handled in https://github.com/w3c/pub-manifest/commit/d0bddcca6f1330c11fd874884e144c7667570f88.

Thank you!

**Comment by mattgarrish** [comment]
Looks like it was possibly a bad merge somewhere along the line, but I believe you deleted the wrong paragraph per this earlier commit:

https://github.com/w3c/wpub/pull/445/files#diff-eacf331f0ffc35d4b482f1d15a887d3bR1490

I'm doing some rearranging to handle the (in)language issue, so I can fix in my branch.
