### ISSUE TITLE
Name of page that links/embeds manifest

### ISSUE THREAD

**Issue by mattgarrish** [w3c/pub-manifest#6]
The "primary entry page" was very specific to the idea of a web publication, but the concept lives on to a small degree in the manifest spec where we need to talk about the page that links to the manifest.

It's named the "publication" entry page for now, but we should review if there's a way to write the term out entirely or if there's an even more general name for it.

**Comment by iherman** [comment]
I guess the main issue is with the term "entry page". We could even use "primary page", though not ideal because it suggests a primary position among the pages of the publication. Alternatively, we can use something like "Manifest Container Page", or "Manifest Page"...

**Comment by laudrain** [comment]
With my Publisher hat, I would propose something that ins very "publishing": the "title page".
In any case that's the sort of page where we would embed the pub manifest as it bears the publication metadata, among them the **title**, called name in Linkde Data...

**Comment by dauwhe** [comment]
> With my Publisher hat, I would propose something that ins very "publishing": the "title page".
> In any case that's the sort of page where we would embed the pub manifest as it bears the publication metadata, among them the **title**, called name in Linkde Data...

But we're not trying to dictate the content of the HTML resource which contains the manifest or the link to the manifest. I think using a name that often already refers to a particular type of content would be confusing.

**Comment by mattgarrish** [comment]
We don't need to refer to the document as anything more than the document that references the manifest, to be honest. I've scrubbed out pep in the proposed PR, as looking at the one reference outside the lifecycle variables it really wasn't what I thought it was.

**Comment by BigBlueHat** [comment]
@mattgarrish by removing the "primary" bit the discovery mechanism becomes pretty unclear. "The document which embeds the manifest" is now anyone's guess.

The advantage of keeping the name (or giving it a new singular name) is that the [Publication Address](https://pr-preview.s3.amazonaws.com/w3c/pub-manifest/pull/19.html#address) MUST return that HTML page, so that discovery can work.

The text around Address has also gotten a bit vague...
> A digital publication MAY have more than one address, but all the addresses MUST resolve to the same document.

"the same document" should really be "the document used for publication manifest discovery" (aka the Primary Entry Page--hence it's name 😄).

**Comment by mattgarrish** [comment]
>  "The document which embeds the manifest" is now anyone's guess.

That's generally the point, yes. We're not defining web publications anymore, or including restrictions related to it, only listing the properties of the manifest.

It'll be up to the specific implementations to determine whether the address is important and what, if anything, it should return, as there's no more inheritance from web publications.
