### ISSUE TITLE
"Processing the manifest": consider adopting the failure/error terminology

### ISSUE THREAD

**Issue by rdeltour** [w3c/pub-manifest#62]
The result of the current algo is either a canonical representation of the manifest or an early termination (which means "the manifest is not valid"). There are also cases where the algo issues a _warning_ but does not terminate.

Most of the other specs we reference (e.g. HTML, URL) instead use a _failure_/_error_ terminology. A failure is returned when the algorithm terminates early. An error is recoverable.

For instance, in the processing model for images [HTML defines _parse errors_](https://html.spec.whatwg.org/#concept-microsyntax-parse-error) as:

> A **parse error** for algorithms in this section indicates a non-fatal mismatch between input and requirements. User agents are encouraged to expose parse errors somehow.

The [URL Standard defines _validation error_](https://url.spec.whatwg.org/#validation-error) as:

> A **validation error** indicates a mismatch between input and valid input. User agents, especially conformance checkers, are encouraged to report them somewhere.
>
> Note: A validation error does not mean that the parser terminates. Termination of a parser is always stated explicitly, e.g., through a return statement.

I suggest we adopt the same terminology in our spec. The more alignment, the easier it is for spec ~~addicts~~ readers.

Also, incidentally, when the spec says:

> If the algorithm terminates early, the manifest is not valid.

I think it is worth noting that the opposite is not necessarily true. For instance when the required _type_ property is missing, a default value of `CreativeWork` will be assumed. I think this would be worth being explicitly clarified.

**Comment by mattgarrish** [comment]
How would the following work for you:

>The steps for processing a manifest into its canonical representation are given by the following algorithm.
> 
> The following error types are used in this algorithm:
> 
>  - A validation error is a non-terminating error that occurs when the value of a property does match its expected input.
> - A fatal error is a terminating error that results, for example, when a manifest cannot be processed or does not match critical validity constraints.
> 
> User agents SHOULD expose both validation and fatal errors, but this specification does not prescribe the manner in which this is done.

We could then replace "error" with "fatal error" and "warning" with "validation error" as that's generally the way they are being used now (using dfn to link these).

(It's probably best not to delve into validity at all.)

**Comment by rdeltour** [comment]
Sounds good to me. It doesn't reuse the _failure_ term used in the other specs I referenced earlier, but as long as we properly define these terms and point back to their definition when we use them, it's OK!

**Comment by mattgarrish** [comment]
>  It doesn't reuse the _failure_ term used in the other specs I referenced earlier

Right, but they don't actually define failure, at least not that I found. Failure is just what is returned. I think we can do that so long as we have the error types defined.

For example, instead of what we say now:

> issue an error and terminate this algorithm

we would instead say:

> issue a fatal error and return failure

**Comment by mattgarrish** [comment]
Or perhaps more in line with the other specs, we could say:

> if ... this is a fatal error. Return failure.

Then we don't have to speak to "issuing" anything in the algorithm.

**Comment by mattgarrish** [comment]
Closing this with #68.
