### ISSUE TITLE
Media type for Publication Manifest

### ISSUE THREAD

**Issue by BigBlueHat** [w3c/pub-manifest#63]
We still have a [Processing the Manifest](https://www.w3.org/TR/pub-manifest/#manifest-processing) section--as noted in https://github.com/w3c/pub-manifest/issues/60#issuecomment-531642918 As long as that exists--i.e. as long as this specification requires more than JSON and/or JSON-LD processing algorithms--it will need it's own media type to signal such processing.

**Comment by iherman** [comment]
See https://github.com/w3c/pub-manifest/issues/60#issuecomment-531645830 (this issue seems to be the same as https://github.com/w3c/pub-manifest/issues/60#issuecomment-531642918)

**Comment by mattgarrish** [comment]
We still define the `rel` type `publication` to trigger processing when a manifest is linked.

I don't like the idea of changing the media type as wasn't the point of using json-ld and its media type to enable web crawlers in the first place?

At any rate, an implementation of the manifest format could always define a media type for the manifest if there was a need for a unique one, just as packaging relies on location and name. We largely stay out of the process of finding the manifest.

**Comment by BigBlueHat** [comment]
How does a processor of these files know they have one of these files and should therefore process it beyond what it is defined by `application/json` and/or `application/ld+json` processing? Is that solely determinable via discovery?

**Comment by BigBlueHat** [comment]
Understand completely. I suppose that's why I'm concerned about going beyond JSON/JSON-LD processing within this specification. Other specs (Verifiable Credentials, Web Annotations, etc) seem to point at just the specification-level required properties, etc. and don't add additional processing such as enforcing defaults, shape changes (author string to author object), and beyond.

ActivityStreams did mint their own media type because they differed from JSON-LD (1.0) by including the possibility of "lists of lists" to embed GeoJSON directly in an ActivityStream.

If/since SEO bots are a target audience for these files, then we would need to (at least when that's a target audience) require both `application/ld+json` as a media type *and* the requirement that it be embedded in HTML via a data block `<script type="..">` tag. Otherwise SEO bots won't consume it.

However, if we (also) must define additional processing, then we need to state how that need for processing is discovered--i.e. what makes "plain" JSON/JSON-LD documents "magic" in the eyes of a consuming application.

Whatever is chosen to do that signalling (media type, discovery system, something in the document), then we'll need to define that/those alongside the definition of the processing steps.

Otherwise, there's no way for a JSON or JSON-LD consumer to know (magically) that they should do something very different (or "beyond") with these documents...because they won't know these require special processing.

**Comment by iherman** [comment]
(I guess what we are talking about (just for other readers) is the possibility of specify an author (or creator, or editor, etc) simply by a name, rather than a requirement to explicitly include in a Person object and, similarly, to use a simple URL string instead a full Linked Resource. In other words, to use those objects only when they are necessary. I believe the other steps are spelling out bona fide JSON-LD steps like arrays vs. elements or expressing language and direction with a text.)

We can repeat the arguments ad nauseam about the pros and cons. Let’s not do this. The change of a media type has profound consequences, so does the imposition of a required object usage even in very simple cases. Do you (or anybody) see a possible compromise or a way out of this? What kind of signal do you have in mind?

**Comment by mattgarrish** [comment]
We discussed this in https://github.com/w3c/wpub/issues/409 and at the Cambridge F2F and agreed that rel=publication was sufficient for this problem.

Why isn't it the case anymore?

**Comment by BigBlueHat** [comment]
> We discussed this in [w3c/wpub#409](https://github.com/w3c/wpub/issues/409) and at the Cambridge F2F and agreed that rel=publication was sufficient for this problem.
> 
> Why isn't it the case anymore?

Because I'd thought (apparently wrongly) that we were defining this publication manifest as a sort of generic manifest JSON format irrespective of its discovery mechanism (i.e. I though discovery steps were being removed or moved to the "profiles").

Publication Manifest still explains discovery, however, and points to other specs creating their own discovery system. Audiobooks still references discovering the manifest out of a "primary entry page."

We can (as agreed in Cambridge) continue to lean on the discovery mechanism(s) as the thing that signals the need for additional processing steps (beyond JSON and beyond JSON-LD). If we do that, however, then defining and *requiring the use of* that discovery mechanism is required--i.e. we need a defined way to signal (and know) that this additional processing algorithm MUST be run.

**Comment by mattgarrish** [comment]
> If we do that, however, then defining and _requiring the use of_ that discovery mechanism is required--i.e. we need a defined way to signal (and know) that this additional processing algorithm MUST be run.

We can require that rel=publication linking always be used in discovery; I have no problem with that. Audiobooks remains compatible with that despite the file naming leniency when packaged.

But I doubt that we can or should build the manifest discovery into the processing steps even if we do require it, for the exact reason that the packaging format defines workarounds to locating the manifest. It's also not the place to be defining primary entry pages or anything like them or else we're just going back to making web publications.

**Comment by BigBlueHat** [comment]
> But I doubt that we can or should build the manifest discovery into the processing steps

Agreed. This is more about how one knows processing steps are even required--not about making the discovery part of the processing steps.
