### ISSUE TITLE
URLs shouldn't be required to dereference to a resource

### ISSUE THREAD

**Issue by rdeltour** [w3c/pub-manifest#67]
Section [2.1.7.5 URLs](https://w3c.github.io/pub-manifest/#value-url) says:

>  URLs MUST dereference to a resource, although user agents are not required to dereference all URLs in the manifest.

This is probably wrong, I don't think anyone can enforce that (it's certainly not testable, at least not in a consistent manner); and 404 are an inherent part of the Web.

Maybe remove that statement?

**Comment by mattgarrish** [comment]
Ya, it's kind of misplaced in the value type section. It's probably better left to profiles to define where resources have to be, and for which properties it matters.
