### ISSUE TITLE
Shouldn't reading order be an array

### ISSUE THREAD

**Issue by clapierre** [w3c/pub-manifest#72]
2.3.1 The PublicationManifest Dictionary

required sequence<LinkedResource>    readingOrder;
like the resources
 sequence<LinkedResource>    resources = [];

I would have expected
required sequence<LinkedResource>    readingOrder = [];

**Comment by mattgarrish** [comment]
@clapierre Wherever you see `sequence<...>`, that's what indicates an array of values is allowed.

The "=" in webidl indicates a default value, so for resources and links the default is an empty sequence/array.

In the case of the reading order, however, the default is to use the document that references the manifest so you never have an empty sequence (without a critical failure). I don't believe there's a way to express that in the webidl, though.

That said, I'm not sure why we specify a default empty sequence for those properties. We don't mention it in the prose or say anything in the processing algorithm. Is there a reason why we expect these to always be present @ivan or can the defaults be removed?

**Comment by iherman** [comment]
I do not remember why the defaults for those. I believe that can be removed.
