### ISSUE TITLE
Using rel="publication"

### ISSUE THREAD

**Issue by HadrienGardeur** [w3c/pub-manifest#8]
I'd like to re-visit our decision to roll our own rel value (`publication`) for detecting the WP manifest.

As I've said in the past, I don't think there's any good reason why we can't use `manifest` instead:

- if we adopt the WAM for our serialization, we'll need to use it anyway
- even if we don't adopt the WAM, the definition for `manifest` is a perfectly fit for our use case (https://w3c.github.io/manifest/#link-relation-type-registration) and we can easily identify the WP manifest using a media type

We could also immediately get rid of the first section of the lifecycle as well, and simply reference the WAM section instead.

I really think that this is a straightforward decision, and an easy win (less spec language and monkey patching in our draft).

**Comment by iherman** [comment]
The decision on WAM has been taken a long time ago. The rel value `manifest` is clearly used for WAM only, per the definition in the WAM spec, the rel value means referring to a manifest, [defined](https://www.w3.org/TR/appmanifest/#dfn-manifest) to be:

> A manifest is a JSON document that contains startup parameters and application defaults for when a web application is launched.

This is clearly not appropriate for the Publication Manifest.

Propose closing.
