### ISSUE TITLE
Minor issue on Identifiers (2.7.1.6.)

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#80]
The text says:

> Identifiers are used to refer to Web Content in a persistent and unambiguous manner

That is probably too restrictive; identifiers can also be used to identify persons (as actually referred to in the definition of entities). 

Probably something like:

> Identifiers are used to refer to Web Content, Persons, or Organizations in a persistent and unumbiguous manner

would be enough for our purposes (without getting into a discussion on what 'identifier' means in general...)

**Comment by mattgarrish** [comment]
LinkedResource doesn't include an `id` property. Is that a mistake?

**Comment by iherman** [comment]
I do not think so. LR is to link out to another resource, and the URL is the right one. In that context there is no need to some sort of a doi, isbn, did, or whatever identification of that resource

**Comment by mattgarrish** [comment]
Okay, it just seems odd that we link to a definition of web content that mentions audio, video, images, css, etc. but then we don't have identifiers for them as linked in the manifest. Maybe I'll tweak that as the scope is narrower.

**Comment by mattgarrish** [comment]
Maybe something like:

> Identifiers are used to to refer to a digital publication and the entities responsible for its creation in a persistent and unambiguous manner.

?

**Comment by iherman** [comment]
Is it 'to a digital publication' or 'to the digital publication'? Ie, do we want to restrict the id to the publication we are talking about in the manifest (I guess yes)?

**Comment by mattgarrish** [comment]
> Is it 'to a digital publication' or 'to the digital publication'?

I would use "a digital publication" at this level. We're talking in the abstract about how this is used for any publication in the definition.

Where we probably have a typo is here:

> A digital publication's canonical identifier property provides a unique identifier for a digital publication.

The second "a" should be a "the" since it's moving into the specific at that point.
