### ISSUE TITLE
Explicit content or for adults only

### ISSUE THREAD

**Issue by gregoriopellegrino** [w3c/pub-manifest#93]
When I looked at Schema.org, I realized that it might be useful to report if a content is explicit (or for adults). It seems to me that podcasts have something similar (at least in the native app on iOs).

Schema.org offers the following properties: isFamilyFriendly, typicalAgeRange

**Comment by mattgarrish** [comment]
This was discussed in https://github.com/w3c/pub-manifest/pull/43

I still have the same concern that if we can't define how to use this property, beyond just make some judgment call as you see fit, it's better to leave it for vendors to define and request it in the metadata in their incoming content. Each will have its own rules, so what one vendor considers family friendly may not be what another does.
