### ISSUE TITLE
Ordering of processing steps v.a.v. conformsTo

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#94]
At the moment, in the [Processing Steps sequence](https://w3c.github.io/pub-manifest/#manifest-processing):

- step (5) checks the values of profile conformance, ie, the values of `conformsTo`
- step (7.e) turns possibly relative URL-s into absolute ones.

The value of `conformsTo` is set to be URL-s, i.e., they can also be relative ones (even if not frequently). Either we have to say that they are always absolute URL-s (which must then be checked), or the order should be reversed. 

I believe if the current step (5) goes after (7) then I believe we are fine.

**Comment by mattgarrish** [comment]
> i.e., they can also be relative ones

Wouldn't that make it a profile local to one file, that changes wherever the file is moved to? What would be an example?

I'd think we either should require absolute URLs or we should be treating conformsTo as a literal that takes a URL as its value. That way if someone were to use a relative URL, which sounds like a keyword in disguise, that relative URL won't get turned into something it isn't later.

**Comment by iherman** [comment]
> I'd think we either should require absolute URLs or we should be treating `conformsTo` as a literal that takes a URL as its value. 

I do not have a problem with that either.

**Comment by mattgarrish** [comment]
Closing this with the merge of #96
