### ISSUE TITLE
constraints on conformsTo?

### ISSUE THREAD

**Issue by iherman** [w3c/pub-manifest#95]
The [processing steps](https://w3c.github.io/pub-manifest/#manifest-processing) include two fairly stringent requirements on the value of `conformsTo` in step (5):

- At least on value of `conformsTo` should refer to a 'recognizable profile' (and this is a possibly fatal error), although we do not talk about what 'recognizable profile' means. We should at least give some details on that in the text, but that can easily lead to some sort of a registry service, for example. I am not sure we should go down that route.
- Only one recognizable profile should be listed. Do we want to be that restrictive? Ie, even if we have recognizable profiles like, say, audiobook or manga, is it out of the question that a manifest would bear _both_ profiles? Is this a restriction we want to build into the manifest spec?

My initial gut feeling is to drop both of these requirements, because it is difficult to check.

**Comment by mattgarrish** [comment]
>     * Only one recognizable profile should be listed. Do we want to be that restrictive?

The processing step doesn't say to ignore others:

> The user agent can select which to give precedence to.

The user agent has to determine what profile(s) it recognizes as it directly affects how it processes the extension steps later. It may also affect how it presents the content - whether as an audio interface or an image one, for example.

The part about being a validation error should go. It may be problematic to have more than one listed, but I suppose that would come out in validation. What if instead it says:

> If manifest["conformsTo"] includes the URLs of more than one recognized profile, the user agent can select which to give precedence to in the case of conflicts.



> although we do not talk about what 'recognizable profile' means

One that it is "capable of processing and/or rendering"?

**Comment by iherman** [comment]
> The part about being a validation error should go. It may be problematic to have more than one listed, but I suppose that would come out in validation. What if instead it says:
>
> "If manifest["conformsTo"] includes the URLs of more than one recognized profile, the user agent can select which to give precedence to in the case of conflicts."

👍  

>> although we do not talk about what 'recognizable profile' means
>
> One that it is "capable of processing and/or rendering"?

Yep.

**Comment by llemeurfr** [comment]
Letting the user agent decide what to do with ambiguous information is a breach in interoperability, isn’t it? I don’t like it.

**Comment by mattgarrish** [comment]
> Letting the user agent decide what to do with ambiguous information is a breach in interoperability

First in the array wins?

**Comment by llemeurfr** [comment]
> Letting the user agent decide what to do with ambiguous information is a breach in interoperability
> 
> First in the array wins?
> 

This is quite logical indeed.

**Comment by mattgarrish** [comment]
Closing this with the merge of #96
